#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Dionatan Simioni'
        hostname: ubuntu-desktop
        username: diolinux
        password: '$y$j9T$b8jTBUu4kJlj2360DQSL21$BGrgjDqpSAQY/hCHlsADcRNFtok8qQSVN0A7kzI5N72'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - gimp
        - git
        - wget
    snaps:
        - name: spotify
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot

